import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex w-full">
          {/* Sidebar section */}
          <aside className="w-64 bg-gray-800 text-white p-4">
            <h2 className="text-xl font-bold mb-4">Sidebar</h2>
            <nav>
              <ul>
                <li>
                  <Link href="/dashboard">Dashboard</Link>
                </li>
              </ul>
              <ul className="mt-4">
                <li>
                  <Link href="/auth">Auth</Link>
                </li>
                <li>
                  <Link href="/user-list">User List</Link>
                </li>
              </ul>
            </nav>
          </aside>

          {/* Nested childern */}
          {children}
        </div>
      </body>
    </html>
  );
}
